### ISSUE TITLE
Current BLEU Score

### ISSUE THREAD

**Issue by loretoparisi** [kefirski/bytenet#1]
Thanks for your work! 
I did not know about the **ByteNet** architecture presented [here](https://arxiv.org/abs/1610.10099). The paper is from Oct 2016 and things in NMT are evolving quickly. Do you know if the current implementation is still state-of-the-art in terms of BLEU score?

**Comment by kefirski** [comment]
As I know, for now [this](https://arxiv.org/abs/1711.02132) model is holding SOTA on NMT task, but my information could be outdated

**Comment by loretoparisi** [comment]
@kefirski Thank you! I was asking since I'm using OpenNMT pre-trained models and [CTranslate](https://github.com/OpenNMT/CTranslate) C++ utility for the inference, then I was considering this network architecture. See [here](http://opennmt.net/Models/)
